2021/02/10-21:10:31 [ERROR]:argsが存在しません
2021/02/10-21:10:44 [INFO ]:DoZipping
2021/02/10-21:10:44 [INFO ]:17件のバックアップを検討します
2021/02/10-21:10:44 [INFO ]:-------D:\Documents\MinecraftAutoBackup\.minecraft\The Unusual SkyBlock v12.0.9\202102102106.zip の検討をします-------
2021/02/10-21:10:44 [INFO ]:zipファイル判定:True
2021/02/10-21:10:44 [INFO ]:-------D:\Documents\MinecraftAutoBackup\.minecraft\The Unusual SkyBlock v12.0.9 - コピー\202102102106.zip の検討をします-------
2021/02/10-21:10:44 [INFO ]:zipファイル判定:True
2021/02/10-21:10:44 [INFO ]:-------D:\Documents\MinecraftAutoBackup\.minecraft\The Unusual SkyBlock v9.1.4\202102102106.zip の検討をします-------
2021/02/10-21:10:44 [INFO ]:zipファイル判定:True
2021/02/10-21:10:44 [INFO ]:-------D:\Documents\MinecraftAutoBackup\.minecraft\The Unusual SkyBlock v9.1.4 - コピー\202102102106.zip の検討をします-------
2021/02/10-21:10:44 [INFO ]:zipファイル判定:True
2021/02/10-21:10:44 [INFO ]:-------D:\Documents\MinecraftAutoBackup\.minecraft\The Water SkyBlock ver2.2.3\202102102106.zip の検討をします-------
2021/02/10-21:10:44 [INFO ]:zipファイル判定:True
2021/02/10-21:10:44 [INFO ]:-------D:\Documents\MinecraftAutoBackup\.minecraft-1.14.4-optifine\a\202102102106.zip の検討をします-------
2021/02/10-21:10:44 [INFO ]:zipファイル判定:True
2021/02/10-21:10:44 [INFO ]:-------D:\Documents\MinecraftAutoBackup\.minecraft-1.14.4-optifine\The Water SkyBlock ver3.1.2\202102102106.zip の検討をします-------
2021/02/10-21:10:44 [INFO ]:zipファイル判定:True
2021/02/10-21:10:44 [INFO ]:-------D:\Documents\MinecraftAutoBackup\.minecraft-1.14.4-optifine\The Water SkyBlock ver3.1.3b\202102102106.zip の検討をします-------
2021/02/10-21:10:44 [INFO ]:zipファイル判定:True
2021/02/10-21:10:44 [INFO ]:-------D:\Documents\MinecraftAutoBackup\.minecraft-1.14.4-optifine\新規ワールド\202102102106.zip の検討をします-------
2021/02/10-21:10:44 [INFO ]:zipファイル判定:True
2021/02/10-21:10:44 [INFO ]:-------D:\Documents\MinecraftAutoBackup\.minecraft-1.14.4-optifine\検証用ワールド\202102102106.zip の検討をします-------
2021/02/10-21:10:44 [INFO ]:zipファイル判定:True
2021/02/10-21:10:44 [INFO ]:-------D:\Documents\MinecraftAutoBackup\.minecraft-1.14.4-optifine\適当建築\202102102106.zip の検討をします-------
2021/02/10-21:10:44 [INFO ]:zipファイル判定:True
2021/02/10-21:10:44 [INFO ]:-------D:\Documents\MinecraftAutoBackup\.minecraft_1.10.2\test\202102102106.zip の検討をします-------
2021/02/10-21:10:44 [INFO ]:zipファイル判定:True
2021/02/10-21:10:44 [INFO ]:-------D:\Documents\MinecraftAutoBackup\.minecraft_1.10.2\The Water SkyBlock ver2.2.3\202102102106.zip の検討をします-------
2021/02/10-21:10:44 [INFO ]:zipファイル判定:True
2021/02/10-21:10:44 [INFO ]:-------D:\Documents\MinecraftAutoBackup\.minecraft_1.9\Rare Species SkyBlock ii Beta2.2.2 (1)\202102102106.zip の検討をします-------
2021/02/10-21:10:44 [INFO ]:zipファイル判定:True
2021/02/10-21:10:44 [INFO ]:-------D:\Documents\MinecraftAutoBackup\.minecraft_forge1.12.2\新規ワールド\202102102106.zip の検討をします-------
2021/02/10-21:10:44 [INFO ]:zipファイル判定:True
2021/02/10-21:10:44 [INFO ]:-------D:\Documents\MinecraftAutoBackup\.minecraft_forge1.12.2\新規ワールド-\202102102106.zip の検討をします-------
2021/02/10-21:10:44 [INFO ]:zipファイル判定:True
2021/02/10-21:10:44 [INFO ]:-------D:\Documents\MinecraftAutoBackup\.minecraft_forge1.12.2\新規ワールド--\202102102106.zip の検討をします-------
2021/02/10-21:10:44 [INFO ]:zipファイル判定:True
2021/02/10-21:10:44 [INFO ]:0件圧縮済み,17件のスルー,0件のエラーが発生しました
2021/02/10-21:16:36 [ERROR]:argsが存在しません
2021/02/10-21:20:52 [INFO ]:DoZipping
2021/02/10-21:20:52 [INFO ]:17件のバックアップを検討します
2021/02/10-21:20:52 [INFO ]:-------D:\Documents\MinecraftAutoBackup\.minecraft\The Unusual SkyBlock v12.0.9\202102102106 の検討をします-------
2021/02/10-21:20:52 [INFO ]:zipファイル判定:False
2021/02/10-21:20:52 [INFO ]:D:\Documents\MinecraftAutoBackup\.minecraft\The Unusual SkyBlock v12.0.9\202102102106 の処理を開始します
2021/02/10-21:20:59 [INFO ]:D:\Documents\MinecraftAutoBackup\.minecraft\The Unusual SkyBlock v12.0.9\202102102106 zip化完了
2021/02/10-21:21:00 [ERROR]:System.UnauthorizedAccessException
2021/02/10-21:21:00 [ERROR]:パス 'D:\Documents\MinecraftAutoBackup\.minecraft\The Unusual SkyBlock v12.0.9\202102102106' へのアクセスが拒否されました。
2021/02/10-21:21:00 [ERROR]:   場所 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   場所 System.IO.File.InternalDelete(String path, Boolean checkHost)
   場所 System.IO.File.Delete(String path)
   場所 DoZipping.Program.Main(String[] args) 場所 C:\Users\YUUKI\source\repos\Minecraft Auto Backup\DoZipping\Program.cs:行 46
2021/02/10-21:21:00 [INFO ]:-------D:\Documents\MinecraftAutoBackup\.minecraft\The Unusual SkyBlock v12.0.9 - コピー\202102102106 の検討をします-------
2021/02/10-21:21:00 [INFO ]:zipファイル判定:False
2021/02/10-21:21:00 [INFO ]:D:\Documents\MinecraftAutoBackup\.minecraft\The Unusual SkyBlock v12.0.9 - コピー\202102102106 の処理を開始します
2021/02/10-21:21:07 [INFO ]:D:\Documents\MinecraftAutoBackup\.minecraft\The Unusual SkyBlock v12.0.9 - コピー\202102102106 zip化完了
2021/02/10-21:21:07 [ERROR]:System.UnauthorizedAccessException
2021/02/10-21:21:07 [ERROR]:パス 'D:\Documents\MinecraftAutoBackup\.minecraft\The Unusual SkyBlock v12.0.9 - コピー\202102102106' へのアクセスが拒否されました。
2021/02/10-21:21:07 [ERROR]:   場所 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   場所 System.IO.File.InternalDelete(String path, Boolean checkHost)
   場所 System.IO.File.Delete(String path)
   場所 DoZipping.Program.Main(String[] args) 場所 C:\Users\YUUKI\source\repos\Minecraft Auto Backup\DoZipping\Program.cs:行 46
2021/02/10-21:21:07 [INFO ]:-------D:\Documents\MinecraftAutoBackup\.minecraft\The Unusual SkyBlock v9.1.4\202102102106 の検討をします-------
2021/02/10-21:21:07 [INFO ]:zipファイル判定:False
2021/02/10-21:21:07 [INFO ]:D:\Documents\MinecraftAutoBackup\.minecraft\The Unusual SkyBlock v9.1.4\202102102106 の処理を開始します
2021/02/10-21:21:10 [INFO ]:D:\Documents\MinecraftAutoBackup\.minecraft\The Unusual SkyBlock v9.1.4\202102102106 zip化完了
2021/02/10-21:21:10 [ERROR]:System.UnauthorizedAccessException
2021/02/10-21:21:10 [ERROR]:パス 'D:\Documents\MinecraftAutoBackup\.minecraft\The Unusual SkyBlock v9.1.4\202102102106' へのアクセスが拒否されました。
2021/02/10-21:21:10 [ERROR]:   場所 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   場所 System.IO.File.InternalDelete(String path, Boolean checkHost)
   場所 System.IO.File.Delete(String path)
   場所 DoZipping.Program.Main(String[] args) 場所 C:\Users\YUUKI\source\repos\Minecraft Auto Backup\DoZipping\Program.cs:行 46
2021/02/10-21:21:10 [INFO ]:-------D:\Documents\MinecraftAutoBackup\.minecraft\The Unusual SkyBlock v9.1.4 - コピー\202102102106 の検討をします-------
2021/02/10-21:21:10 [INFO ]:zipファイル判定:False
2021/02/10-21:21:10 [INFO ]:D:\Documents\MinecraftAutoBackup\.minecraft\The Unusual SkyBlock v9.1.4 - コピー\202102102106 の処理を開始します
2021/02/10-21:21:12 [INFO ]:D:\Documents\MinecraftAutoBackup\.minecraft\The Unusual SkyBlock v9.1.4 - コピー\202102102106 zip化完了
2021/02/10-21:21:12 [ERROR]:System.UnauthorizedAccessException
2021/02/10-21:21:12 [ERROR]:パス 'D:\Documents\MinecraftAutoBackup\.minecraft\The Unusual SkyBlock v9.1.4 - コピー\202102102106' へのアクセスが拒否されました。
2021/02/10-21:21:12 [ERROR]:   場所 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   場所 System.IO.File.InternalDelete(String path, Boolean checkHost)
   場所 System.IO.File.Delete(String path)
   場所 DoZipping.Program.Main(String[] args) 場所 C:\Users\YUUKI\source\repos\Minecraft Auto Backup\DoZipping\Program.cs:行 46
2021/02/10-21:21:12 [INFO ]:-------D:\Documents\MinecraftAutoBackup\.minecraft\The Water SkyBlock ver2.2.3\202102102106 の検討をします-------
2021/02/10-21:21:12 [INFO ]:zipファイル判定:False
2021/02/10-21:21:12 [INFO ]:D:\Documents\MinecraftAutoBackup\.minecraft\The Water SkyBlock ver2.2.3\202102102106 の処理を開始します
2021/02/10-21:21:13 [INFO ]:D:\Documents\MinecraftAutoBackup\.minecraft\The Water SkyBlock ver2.2.3\202102102106 zip化完了
2021/02/10-21:21:13 [ERROR]:System.UnauthorizedAccessException
2021/02/10-21:21:13 [ERROR]:パス 'D:\Documents\MinecraftAutoBackup\.minecraft\The Water SkyBlock ver2.2.3\202102102106' へのアクセスが拒否されました。
2021/02/10-21:21:13 [ERROR]:   場所 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   場所 System.IO.File.InternalDelete(String path, Boolean checkHost)
   場所 System.IO.File.Delete(String path)
   場所 DoZipping.Program.Main(String[] args) 場所 C:\Users\YUUKI\source\repos\Minecraft Auto Backup\DoZipping\Program.cs:行 46
2021/02/10-21:21:13 [INFO ]:-------D:\Documents\MinecraftAutoBackup\.minecraft-1.14.4-optifine\a\202102102106 の検討をします-------
2021/02/10-21:21:13 [INFO ]:zipファイル判定:False
2021/02/10-21:21:13 [INFO ]:D:\Documents\MinecraftAutoBackup\.minecraft-1.14.4-optifine\a\202102102106 の処理を開始します
2021/02/10-21:21:16 [INFO ]:D:\Documents\MinecraftAutoBackup\.minecraft-1.14.4-optifine\a\202102102106 zip化完了
2021/02/10-21:21:16 [ERROR]:System.UnauthorizedAccessException
2021/02/10-21:21:16 [ERROR]:パス 'D:\Documents\MinecraftAutoBackup\.minecraft-1.14.4-optifine\a\202102102106' へのアクセスが拒否されました。
2021/02/10-21:21:16 [ERROR]:   場所 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   場所 System.IO.File.InternalDelete(String path, Boolean checkHost)
   場所 System.IO.File.Delete(String path)
   場所 DoZipping.Program.Main(String[] args) 場所 C:\Users\YUUKI\source\repos\Minecraft Auto Backup\DoZipping\Program.cs:行 46
2021/02/10-21:21:16 [INFO ]:-------D:\Documents\MinecraftAutoBackup\.minecraft-1.14.4-optifine\The Water SkyBlock ver3.1.2\202102102106 の検討をします-------
2021/02/10-21:21:16 [INFO ]:zipファイル判定:False
2021/02/10-21:21:16 [INFO ]:D:\Documents\MinecraftAutoBackup\.minecraft-1.14.4-optifine\The Water SkyBlock ver3.1.2\202102102106 の処理を開始します
2021/02/10-21:21:20 [INFO ]:D:\Documents\MinecraftAutoBackup\.minecraft-1.14.4-optifine\The Water SkyBlock ver3.1.2\202102102106 zip化完了
2021/02/10-21:21:20 [ERROR]:System.UnauthorizedAccessException
2021/02/10-21:21:20 [ERROR]:パス 'D:\Documents\MinecraftAutoBackup\.minecraft-1.14.4-optifine\The Water SkyBlock ver3.1.2\202102102106' へのアクセスが拒否されました。
2021/02/10-21:21:20 [ERROR]:   場所 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   場所 System.IO.File.InternalDelete(String path, Boolean checkHost)
   場所 System.IO.File.Delete(String path)
   場所 DoZipping.Program.Main(String[] args) 場所 C:\Users\YUUKI\source\repos\Minecraft Auto Backup\DoZipping\Program.cs:行 46
2021/02/10-21:21:20 [INFO ]:-------D:\Documents\MinecraftAutoBackup\.minecraft-1.14.4-optifine\The Water SkyBlock ver3.1.3b\202102102106 の検討をします-------
2021/02/10-21:21:20 [INFO ]:zipファイル判定:False
2021/02/10-21:21:20 [INFO ]:D:\Documents\MinecraftAutoBackup\.minecraft-1.14.4-optifine\The Water SkyBlock ver3.1.3b\202102102106 の処理を開始します
2021/02/10-21:21:26 [INFO ]:D:\Documents\MinecraftAutoBackup\.minecraft-1.14.4-optifine\The Water SkyBlock ver3.1.3b\202102102106 zip化完了
2021/02/10-21:21:26 [ERROR]:System.UnauthorizedAccessException
2021/02/10-21:21:26 [ERROR]:パス 'D:\Documents\MinecraftAutoBackup\.minecraft-1.14.4-optifine\The Water SkyBlock ver3.1.3b\202102102106' へのアクセスが拒否されました。
2021/02/10-21:21:26 [ERROR]:   場所 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   場所 System.IO.File.InternalDelete(String path, Boolean checkHost)
   場所 System.IO.File.Delete(String path)
   場所 DoZipping.Program.Main(String[] args) 場所 C:\Users\YUUKI\source\repos\Minecraft Auto Backup\DoZipping\Program.cs:行 46
2021/02/10-21:21:26 [INFO ]:-------D:\Documents\MinecraftAutoBackup\.minecraft-1.14.4-optifine\新規ワールド\202102102106 の検討をします-------
2021/02/10-21:21:26 [INFO ]:zipファイル判定:False
2021/02/10-21:21:26 [INFO ]:D:\Documents\MinecraftAutoBackup\.minecraft-1.14.4-optifine\新規ワールド\202102102106 の処理を開始します
2021/02/10-21:21:26 [INFO ]:D:\Documents\MinecraftAutoBackup\.minecraft-1.14.4-optifine\新規ワールド\202102102106 zip化完了
2021/02/10-21:21:26 [ERROR]:System.UnauthorizedAccessException
2021/02/10-21:21:26 [ERROR]:パス 'D:\Documents\MinecraftAutoBackup\.minecraft-1.14.4-optifine\新規ワールド\202102102106' へのアクセスが拒否されました。
2021/02/10-21:21:26 [ERROR]:   場所 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   場所 System.IO.File.InternalDelete(String path, Boolean checkHost)
   場所 System.IO.File.Delete(String path)
   場所 DoZipping.Program.Main(String[] args) 場所 C:\Users\YUUKI\source\repos\Minecraft Auto Backup\DoZipping\Program.cs:行 46
2021/02/10-21:21:26 [INFO ]:-------D:\Documents\MinecraftAutoBackup\.minecraft-1.14.4-optifine\検証用ワールド\202102102106 の検討をします-------
2021/02/10-21:21:26 [INFO ]:zipファイル判定:False
2021/02/10-21:21:26 [INFO ]:D:\Documents\MinecraftAutoBackup\.minecraft-1.14.4-optifine\検証用ワールド\202102102106 の処理を開始します
2021/02/10-21:21:26 [INFO ]:D:\Documents\MinecraftAutoBackup\.minecraft-1.14.4-optifine\検証用ワールド\202102102106 zip化完了
2021/02/10-21:21:26 [ERROR]:System.UnauthorizedAccessException
2021/02/10-21:21:26 [ERROR]:パス 'D:\Documents\MinecraftAutoBackup\.minecraft-1.14.4-optifine\検証用ワールド\202102102106' へのアクセスが拒否されました。
2021/02/10-21:21:26 [ERROR]:   場所 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   場所 System.IO.File.InternalDelete(String path, Boolean checkHost)
   場所 System.IO.File.Delete(String path)
   場所 DoZipping.Program.Main(String[] args) 場所 C:\Users\YUUKI\source\repos\Minecraft Auto Backup\DoZipping\Program.cs:行 46
2021/02/10-21:21:26 [INFO ]:-------D:\Documents\MinecraftAutoBackup\.minecraft-1.14.4-optifine\適当建築\202102102106 の検討をします-------
2021/02/10-21:21:26 [INFO ]:zipファイル判定:False
2021/02/10-21:21:26 [INFO ]:D:\Documents\MinecraftAutoBackup\.minecraft-1.14.4-optifine\適当建築\202102102106 の処理を開始します
2021/02/10-21:21:26 [INFO ]:D:\Documents\MinecraftAutoBackup\.minecraft-1.14.4-optifine\適当建築\202102102106 zip化完了
2021/02/10-21:21:26 [ERROR]:System.UnauthorizedAccessException
2021/02/10-21:21:26 [ERROR]:パス 'D:\Documents\MinecraftAutoBackup\.minecraft-1.14.4-optifine\適当建築\202102102106' へのアクセスが拒否されました。
2021/02/10-21:21:26 [ERROR]:   場所 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   場所 System.IO.File.InternalDelete(String path, Boolean checkHost)
   場所 System.IO.File.Delete(String path)
   場所 DoZipping.Program.Main(String[] args) 場所 C:\Users\YUUKI\source\repos\Minecraft Auto Backup\DoZipping\Program.cs:行 46
2021/02/10-21:21:26 [INFO ]:-------D:\Documents\MinecraftAutoBackup\.minecraft_1.10.2\test\202102102106 の検討をします-------
2021/02/10-21:21:26 [INFO ]:zipファイル判定:False
2021/02/10-21:21:26 [INFO ]:D:\Documents\MinecraftAutoBackup\.minecraft_1.10.2\test\202102102106 の処理を開始します
2021/02/10-21:21:26 [INFO ]:D:\Documents\MinecraftAutoBackup\.minecraft_1.10.2\test\202102102106 zip化完了
2021/02/10-21:21:26 [ERROR]:System.UnauthorizedAccessException
2021/02/10-21:21:26 [ERROR]:パス 'D:\Documents\MinecraftAutoBackup\.minecraft_1.10.2\test\202102102106' へのアクセスが拒否されました。
2021/02/10-21:21:26 [ERROR]:   場所 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   場所 System.IO.File.InternalDelete(String path, Boolean checkHost)
   場所 System.IO.File.Delete(String path)
   場所 DoZipping.Program.Main(String[] args) 場所 C:\Users\YUUKI\source\repos\Minecraft Auto Backup\DoZipping\Program.cs:行 46
2021/02/10-21:21:26 [INFO ]:-------D:\Documents\MinecraftAutoBackup\.minecraft_1.10.2\The Water SkyBlock ver2.2.3\202102102106 の検討をします-------
2021/02/10-21:21:26 [INFO ]:zipファイル判定:False
2021/02/10-21:21:26 [INFO ]:D:\Documents\MinecraftAutoBackup\.minecraft_1.10.2\The Water SkyBlock ver2.2.3\202102102106 の処理を開始します
2021/02/10-21:21:27 [INFO ]:D:\Documents\MinecraftAutoBackup\.minecraft_1.10.2\The Water SkyBlock ver2.2.3\202102102106 zip化完了
2021/02/10-21:21:27 [ERROR]:System.UnauthorizedAccessException
2021/02/10-21:21:27 [ERROR]:パス 'D:\Documents\MinecraftAutoBackup\.minecraft_1.10.2\The Water SkyBlock ver2.2.3\202102102106' へのアクセスが拒否されました。
2021/02/10-21:21:27 [ERROR]:   場所 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   場所 System.IO.File.InternalDelete(String path, Boolean checkHost)
   場所 System.IO.File.Delete(String path)
   場所 DoZipping.Program.Main(String[] args) 場所 C:\Users\YUUKI\source\repos\Minecraft Auto Backup\DoZipping\Program.cs:行 46
2021/02/10-21:21:27 [INFO ]:-------D:\Documents\MinecraftAutoBackup\.minecraft_1.9\Rare Species SkyBlock ii Beta2.2.2 (1)\202102102106 の検討をします-------
2021/02/10-21:21:27 [INFO ]:zipファイル判定:False
2021/02/10-21:21:27 [INFO ]:D:\Documents\MinecraftAutoBackup\.minecraft_1.9\Rare Species SkyBlock ii Beta2.2.2 (1)\202102102106 の処理を開始します
2021/02/10-21:21:31 [INFO ]:D:\Documents\MinecraftAutoBackup\.minecraft_1.9\Rare Species SkyBlock ii Beta2.2.2 (1)\202102102106 zip化完了
2021/02/10-21:21:31 [ERROR]:System.UnauthorizedAccessException
2021/02/10-21:21:31 [ERROR]:パス 'D:\Documents\MinecraftAutoBackup\.minecraft_1.9\Rare Species SkyBlock ii Beta2.2.2 (1)\202102102106' へのアクセスが拒否されました。
2021/02/10-21:21:31 [ERROR]:   場所 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   場所 System.IO.File.InternalDelete(String path, Boolean checkHost)
   場所 System.IO.File.Delete(String path)
   場所 DoZipping.Program.Main(String[] args) 場所 C:\Users\YUUKI\source\repos\Minecraft Auto Backup\DoZipping\Program.cs:行 46
2021/02/10-21:21:31 [INFO ]:-------D:\Documents\MinecraftAutoBackup\.minecraft_forge1.12.2\新規ワールド\202102102106 の検討をします-------
2021/02/10-21:21:31 [INFO ]:zipファイル判定:False
2021/02/10-21:21:31 [INFO ]:D:\Documents\MinecraftAutoBackup\.minecraft_forge1.12.2\新規ワールド\202102102106 の処理を開始します
2021/02/10-21:21:32 [INFO ]:D:\Documents\MinecraftAutoBackup\.minecraft_forge1.12.2\新規ワールド\202102102106 zip化完了
2021/02/10-21:21:32 [ERROR]:System.UnauthorizedAccessException
2021/02/10-21:21:32 [ERROR]:パス 'D:\Documents\MinecraftAutoBackup\.minecraft_forge1.12.2\新規ワールド\202102102106' へのアクセスが拒否されました。
2021/02/10-21:21:32 [ERROR]:   場所 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   場所 System.IO.File.InternalDelete(String path, Boolean checkHost)
   場所 System.IO.File.Delete(String path)
   場所 DoZipping.Program.Main(String[] args) 場所 C:\Users\YUUKI\source\repos\Minecraft Auto Backup\DoZipping\Program.cs:行 46
2021/02/10-21:21:32 [INFO ]:-------D:\Documents\MinecraftAutoBackup\.minecraft_forge1.12.2\新規ワールド-\202102102106 の検討をします-------
2021/02/10-21:21:32 [INFO ]:zipファイル判定:False
2021/02/10-21:21:32 [INFO ]:D:\Documents\MinecraftAutoBackup\.minecraft_forge1.12.2\新規ワールド-\202102102106 の処理を開始します
2021/02/10-21:21:32 [INFO ]:D:\Documents\MinecraftAutoBackup\.minecraft_forge1.12.2\新規ワールド-\202102102106 zip化完了
2021/02/10-21:21:32 [ERROR]:System.UnauthorizedAccessException
2021/02/10-21:21:32 [ERROR]:パス 'D:\Documents\MinecraftAutoBackup\.minecraft_forge1.12.2\新規ワールド-\202102102106' へのアクセスが拒否されました。
2021/02/10-21:21:32 [ERROR]:   場所 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   場所 System.IO.File.InternalDelete(String path, Boolean checkHost)
   場所 System.IO.File.Delete(String path)
   場所 DoZipping.Program.Main(String[] args) 場所 C:\Users\YUUKI\source\repos\Minecraft Auto Backup\DoZipping\Program.cs:行 46
2021/02/10-21:21:32 [INFO ]:-------D:\Documents\MinecraftAutoBackup\.minecraft_forge1.12.2\新規ワールド--\202102102106 の検討をします-------
2021/02/10-21:21:33 [INFO ]:zipファイル判定:False
2021/02/10-21:21:33 [INFO ]:D:\Documents\MinecraftAutoBackup\.minecraft_forge1.12.2\新規ワールド--\202102102106 の処理を開始します
2021/02/10-21:21:33 [INFO ]:D:\Documents\MinecraftAutoBackup\.minecraft_forge1.12.2\新規ワールド--\202102102106 zip化完了
2021/02/10-21:21:33 [ERROR]:System.UnauthorizedAccessException
2021/02/10-21:21:33 [ERROR]:パス 'D:\Documents\MinecraftAutoBackup\.minecraft_forge1.12.2\新規ワールド--\202102102106' へのアクセスが拒否されました。
2021/02/10-21:21:33 [ERROR]:   場所 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   場所 System.IO.File.InternalDelete(String path, Boolean checkHost)
   場所 System.IO.File.Delete(String path)
   場所 DoZipping.Program.Main(String[] args) 場所 C:\Users\YUUKI\source\repos\Minecraft Auto Backup\DoZipping\Program.cs:行 46
2021/02/10-21:21:33 [INFO ]:0件圧縮済み,0件のスルー,17件のエラーが発生しました
